### ISSUE TITLE
飞书登录授权码

### ISSUE THREAD

**Issue by Cancer-API** [BlueSkyXN/Feishu-Bitable-Python-API#1]
请问飞书的登录授权码怎么获取到呢？

**Comment by BlueSkyXN** [comment]
> 请问飞书的登录授权码怎么获取到呢？

参考官方文档 https://open.feishu.cn/document/server-docs/authentication-management/login-state-management/obtain-code
这种没稳定的项目你都能找到啊

**Comment by BlueSkyXN** [comment]
> 请问飞书的登录授权码怎么获取到呢？

对应的Py文件

https://github.com/BlueSkyXN/Feishu-Bitable-Python-API/blob/main/GET_LOGIN_CODE.py

**Comment by wxingheng** [comment]
![image](https://github.com/BlueSkyXN/Feishu-Bitable-Python-API/assets/20256886/636eb253-b6c7-416b-8392-e37ce4c3326a)


![image](https://github.com/BlueSkyXN/Feishu-Bitable-Python-API/assets/20256886/4ae5cebd-9d6b-478c-bab4-fe0de1e4e2dc)

大佬，可以帮忙看下这个是什么问题吗
